name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo "Environment ist ${{ inputs.environment }}"
      - run: echo "Hallo ${{ vars.DESCRIPTION }}"
      - run: echo "Mein Benutzer-Secret ist ${{ secrets.MONGODB_USERNAME }}"
